name: CI
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake ninja-build clang-tidy cppcheck gcc-arm-none-eabi

      # Host (PC) build
      - name: Configure (host)
        run: cmake -B build_host -G Ninja -DCMAKE_BUILD_TYPE=Release
      - name: Build (host)
        run: cmake --build build_host
      - name: Run host test
        run: ./build_host/host_test

      # ARM cross build (no executable, only static lib)
      - name: Configure (ARM)
        run: |
          cmake -B build_arm -G Ninja \
            -DCMAKE_C_COMPILER=arm-none-eabi-gcc \
            -DCMAKE_SYSTEM_NAME=Generic \
            -DCMAKE_TRY_COMPILE_TARGET_TYPE=STATIC_LIBRARY \
            -DCMAKE_C_FLAGS="-mcpu=cortex-m7 -mthumb --specs=nosys.specs"
      - name: Build (ARM)
        run: cmake --build build_arm

      # Lint: versions as smoke check (later: apply to files)
      - name: Lint (versions)
        run: |
          clang-tidy --version
          cppcheck --version
